<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnnoDesigner.Core\AnnoDesigner.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>
  <PropertyGroup />
</Project>